name: Build SORT

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v3
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Get Cache Directory
      id: cache-dir
      run: |
          echo ::set-output name=dir::%CD%
      shell: cmd
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: Windows-dep-ver-60
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: make update_dep
      shell: cmd
    - name: Build Release Version
      run: make release
      shell: cmd
    - name: Build Debug Version
      run: make debug
      shell: cmd
    - name: Verify Build
      run: make verify_builds
      shell: cmd
    - name: Unit Test
      run: |
           cd bin
           sort_r.exe --unittest
      shell: cmd
  MacOs_Intel:
    runs-on: macOS-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v3
    - name: Get Cache Directory
      id: cache-dir
      run: echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: MacOS-Intel-dep-ver-60
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: |
           brew install flex
           brew install bison
           echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
           source ~/.bash_profile
           bison -V
           make update_dep ARCH=x86_64
    - name: Build Release Version
      run: make release ARCH=x86_64
    - name: Build Debug Version
      run: make debug ARCH=x86_64
    - name: Verify Build
      run: make verify_builds
    - name: Unit Test
      run: cd bin;./sort_r --unittest
  MacOS_Apple_Silicon:
    runs-on: macOS-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v3
    - name: Get Cache Directory
      id: cache-dir
      run: echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: MacOS-Apple-Silicon-dep-ver-60
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: |
           brew install flex
           brew install bison
           echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
           source ~/.bash_profile
           bison -V
           make update_dep ARCH=arm64
    - name: Build Release Version
      run: make release ARCH=arm64
    - name: Build Debug Version
      run: make debug ARCH=arm64
    - name: Verify Build
      run: make verify_builds
  Ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v3
    - name: Get Cache Directory
      id: cache-dir
      run: echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: Ubuntu-20-04-dep-ver-60
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: |
           sudo apt-get install flex
           sudo apt-get install bison
           make update_dep
    - name: Build Release Version
      run: make release
    - name: Build Debug Version
      run: make debug
    - name: Verify Build
      run: make verify_builds
    - name: Unit Test
      run: cd bin;./sort_r --unittest
  Ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v3
    - name: Get Cache Directory
      id: cache-dir
      run: echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: Ubuntu-18-04-dep-ver-60
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: |
           sudo apt-get install flex
           sudo apt-get install bison
           make update_dep
    - name: Build Release Version
      run: make release
    - name: Build Debug Version
      run: make debug
    - name: Verify Build
      run: make verify_builds
    - name: Unit Test
      run: cd bin;./sort_r --unittest